module.exports = {
  Person: require("./person"),
  Poll: require("./poll"),
  Birthday: require("./birthday"),
  VoiceMasterConfig: require("./voicemaster-config"),
  TempVoiceChannel: require("./temp-voice-channel"),
  UserPoints: require("./user-points"),
  Prediction: require("./prediction"),
  GuildPointsConfig: require("./guild-points-config"),
  Pet: require("./pet"),
  PetTournament: require("./pet-tournament"),
  Lottery: require("./lottery"),
  LogConfig: require("./log-config"),
  MessageLogCache: require("./message-log-cache"),
  Player: require("./player"),
  Match: require("./match"),
  PlayerMatchStat: require("./player-match-stat"),
};
